*THIS IS WORK IN PROGRESS*

*PRE-ALPHA*

* org-pm

Publish org-mode files or sections to projects created GB reading specifications from a folder.
** Features / Principles

- Publish any Org-mode file or any section of it to any number of projects.
- Zero configuration: Start publishing any file or section to an existing or new project, without having to previously configure the system at all.
- Easy customization: Write the html, org-mode options, css and JavaScript files that are needed to customize export in files, and have these be included in the project automatically.
** Directory structure
*** Project directory

Org-pm stores the configuration, source, and export files for all projects in a single directory.  The default location of this directory is ~/org-pm-projects. Each sub-directory of this directory holds a project.

For example, the following directory structure defines two projects, =project1= and =project2=:

#+BEGIN_EXAMPLE
~/org-pm-projects
                 /project1
                 /project2
#+END_EXAMPLE

Each project directory has the following structure:
- Directory =CONFIG= :: Contains =html= and =org= files used to configure the org-mode options of the project and provide headers and other html parts.
- Directory =includes= :: Contains =css= and =js= files that are included in the final project's pages through the standard header mechanism.
- Directory =scripts= :: Contains shell scripts for deploying the site.

The project's html is exported inside the top level of the project folder.

Here is an example of a project folder:

#+BEGIN_EXAMPLE
: project1
    directory CONFIG:
          options.org      (contains the options for configuring export)
          HTML_HEADER.html (contains the HTML_HEADER part for export)
    directory includes:
          style.css (contains the css style definition for the site)
          scripts.min.js (contains js scripts for the site)
    directory SOURCE:
          index.org (the home page, created by exporting through org-pm)
    directory scripts:
          github.sh (shell script for deploying the site to github)
    index.html  (the home page, generated by org-pm-publish from index.org
#+END_EXAMPLE

**** The =SOURCE= directory

=org-pm= places the org files that are used to create the project site inside the SOURCE folder.

*** Templates directory

/Note: Feature in preparation: Templates directory.  The templates directory will hold templates for creating new projects with different styles and options./
