*THIS IS WORK IN PROGRESS*

*PRE-ALPHA*

* org-pm

Publish org-mode files or sections to projects created GB reading specifications from a folder.
** Features / Principles

- Publish any Org-mode file or any section of it to any number of projects.
- Zero configuration: Start publishing any file or section to an existing or new project, without any previous configuration.
- Easy customization: Place html (header), org-mode options, css and JavaScript files in folders =CONFIG= and =includes=, and they are included in the projects definition automatically.
** Installation, dependencies

=org-pm= can be obtained from GitHub at: https://github.com/iani/org-pm

The =el-get= recipe for =org-pm= is:

#+BEGIN_SRC elisp
(:name org-pm :url "http://github.com/iani/org-pm.git" :type git :features
       (org-pm)
       :after nil)
#+END_SRC

=org-pm= uses following packages:

1. =grizzl=
2. =dash=

** Directory structure
*** Project directory

Org-pm stores the configuration, source, and export files for all projects in a single directory.  The default location of this directory is ~/org-pm-projects. Each sub-directory of this directory holds a project.

For example, the following directory structure defines two projects, =project1= and =project2=:

#+BEGIN_EXAMPLE
~/org-pm-projects
                 /project1
                 /project2
#+END_EXAMPLE

=org-pm= stores the =Org-mode= source files of the project in the projects' directory, under sub-directory =SOURCE=.  The exported files output by publishing the project are placed directly inside the top level of the project directory.  The project =SOURCE= directory is scanned recursively, and the directory structure of the source is preserved in the exported files directory structure.

Furthermore, each project directory may optionally contain the following sub-directories:
- Directory =CONFIG= :: Contains =html= and =org= files used to configure the org-mode options of the project and provide headers and other html parts.
- Directory =includes= :: Contains =css= and =js= files that are included in the final project's pages through the standard header mechanism.
- Directory =DEPLOY= :: Contains shell scripts for deploying the site.

The project's html is exported inside the top level of the project folder.

#+BEGIN_EXAMPLE
project1
    directory CONFIG:
          options.org      (contains the options for configuring export)
          HTML_HEAD.html   (contains the HTML_HEAD part for export)
    directory includes:
          style.css        (contains the css style definition for the site)
          scripts.min.js   (contains js scripts for the site)
    directory SOURCE:
          index.org        (the home page, created by publishing with org-pm)
    directory DEPLOY:
          github.sh        (shell script for deploying the site to github)
    index.html             (the home page, generated by org-pm-publish from index.org)
#+END_EXAMPLE

**** The =SOURCE= directory

=org-pm= places the org files that are used to create the project site inside the SOURCE folder.

*** Templates directory

/Note: Feature in preparation: Templates directory.  The templates directory will hold templates for creating new projects with different styles and options./
