* Appendix: Re-designing the menu with JavaScript and CSS

This is a good candidate for remaking the contents menu: http://mmenu.frebsite.nl/

Two alternatives for going to a section when clicking its link on the contents menu:

1. Scroll to the section.
2. Show the section alone, while hiding all other contents on the main page.

Alternative 2 is better for large files, especially if they also contain pictures which may slow down the loading of the page if they are all loaded at once.  Notes on how to implement showing one section only.
** Hide all org-mode sections per default

Upon loading the page, all sections should be hidden per default.  This is done in CSS by specifying =display: none= as property for style class =outline-2=:

#+BEGIN_SRC css
.outline-2 {
     display: none;
}
#+END_SRC

To un-hide any section and display it in a fixed position (near the top of the page), while also dynamically re-positioning any other permanent elements in the page, such as a post-amble credits section, the following technique can be used.  The technique has three parts, shown in the following sections.

** Create an empty placeholder =div= where the selected section will be displayed

At the top of the org-mode document, insert the following code for the placeholder:

: #+BEGIN_HTML
: <div id="currentSection"><div id="currentChild"></div></div>
: #+END_HTML

** Create a JavaScript function for cloning any section and showing it inside the placeholder =div=

#+BEGIN_SRC js
  function cloneAppendVisible (section2display) {
      var newChild, targetNode;
      targetNode = document.getElementById("currentSection");
      newChild = document.getElementById(section2display).cloneNode(true);
      targetNode.replaceChild(newChild, targetNode.firstChild);
      newChild.style.display="block";
  }
#+END_SRC
** Call the function for showing sections in the placeholder

Here are some buttons for testing the above technique.  A variant of this code should be integrated in the navigation menu.

: #+BEGIN_HTML
: <button type="button" onclick="cloneAppendVisible('outline-container-sec-1')">
: replace child test 1
: </button>
: <button type="button" onclick="cloneAppendVisible('outline-container-sec-2')">
: replace child test 2
: </button>
: <button type="button" onclick="cloneAppendVisible('outline-container-sec-1-1')">
: show subsection test
: </button>
: #+END_HTML
** Initialize: Show the first section only when loading
One may initialize the page to show only the first section when loading, by inserting the following code at the bottom of the org-mode file:

: #+BEGIN_HTML
: <script>cloneAppendVisible("outline-container-sec-1")</script>
: #+END_HTML
